var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Lun",
            "mon": "Mar",
            "tue": "Mer",
            "wed": "Jeu",
            "thu": "Ven",
            "fri": "Sam",
            "sat": "Dim",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Juin",
            "jul": "Juil",
            "aug": "Aou",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "Pas encore implémenté",
        "to_date_view": "Clickez sur la date courrante",
        "i_undefined": "Non renseigné",
        "allday_event": "Toute la journée",
        "repeat_event": "Répéter l'évènement",
        "time": "Heure",
        "event": "Evènement",
        "location": "Emplacement",
        "participant": "Participant",
        "get_data_exception": "Exception lors de l'obtention des données",
        "new_event": "Nouvel évènement",
        "confirm_delete_event": "Etes-vous sûr de vouloir supprimer cet évènement? ",
        "confrim_delete_event_or_all": "Voulez-vous supprimer toutes les répétitions de cet évènement? \r\n[OK] pour supprimer uniquement cet évènement, [Cancel] pour supprimer toutes les répétitions",
        "data_format_error": "Erreur format de données! ",
        "invalid_title": "Le titre de l'évènement ne peux être vide ou contenir les caractères ($<>)",
        "view_no_ready": "La vue n'est pas prête",
        "example": "e.g., rdv d'affaire",
        "content": "Quoi",
        "create_event": "Créer un évènement",
        "update_detail": "Editer les détails",
        "click_to_detail": "Consulter les détails",
        "i_delete": "Supprimer",
        "day_plural": "Jours",
        "others": "Autres",
        "item": ""
    }
});
